---
title: "05_analysis_2"
format: html
editor: visual
---

## PCA plot

move to augment if it works

```{r}
sample_table_DEseq_2 <- sample_table_DEseq |>
  left_join(
    clinical_data_augment |>
      select(sample, race.demographic, gender.demographic, ajcc_pathologic_stage.diagnoses, vital_status.demographic, tissue_or_organ_of_origin.diagnoses, ajcc_pathologic_m.diagnoses),
    by="sample")
```

```{r}
pca_fit <- normalized_counts_flipped |>
  select(where(is.numeric)) |>
  select(where(~sum(.)!=0)) |>
  select(all_of(significant_genes$gene)) |>
  prcomp(scale = TRUE) 

```

```{r}
variance_explained <- summary(pca_fit)$importance[2, ] * 100  
pc1_var <- round(variance_explained[1], 2)  
pc2_var <- round(variance_explained[2], 2)

```

```{r}
pca_fit |> 
  augment(sample_table_DEseq_2[match(rownames(normalized_counts_flipped), sample_table_DEseq[[1]]), ]) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = gender.demographic)) +
  geom_point(size=1.5)  +
  labs(
    x = paste0("PC1 (", pc1_var, "% variance)"),
    y = paste0("PC2 (", pc2_var, "% variance)"),
    title = "PCA Plot"
  ) +
  theme_minimal()
```

```{r}
pca_fit |> 
  augment(sample_table_DEseq_2[match(rownames(normalized_counts_flipped), sample_table_DEseq[[1]]), ]) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = race.demographic)) +
  geom_point(size=1.5)  +
  labs(
    x = paste0("PC1 (", pc1_var, "% variance)"),
    y = paste0("PC2 (", pc2_var, "% variance)"),
    title = "PCA Plot"
  ) +
  theme_minimal()
```

```{r}
pca_fit |> 
  augment(sample_table_DEseq_2[match(rownames(normalized_counts_flipped), sample_table_DEseq[[1]]), ]) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = ajcc_pathologic_stage.diagnoses)) +
  geom_point(size=1.5)  +
  labs(
    x = paste0("PC1 (", pc1_var, "% variance)"),
    y = paste0("PC2 (", pc2_var, "% variance)"),
    title = "PCA Plot"
  ) +
  theme_minimal()
```

```{r}
pca_fit |> 
  augment(sample_table_DEseq_2[match(rownames(normalized_counts_flipped), sample_table_DEseq[[1]]), ]) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = ajcc_pathologic_m.diagnoses)) +
  geom_point(size=1.5)  +
  labs(
    x = paste0("PC1 (", pc1_var, "% variance)"),
    y = paste0("PC2 (", pc2_var, "% variance)"),
    title = "PCA Plot"
  ) +
  theme_minimal()
```
